# Generated by Django 3.1.2 on 2021-02-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashApi', '0002_cashflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
